version: "3.9"

services:
  web:
    build: .
    container_name: transaction_service_web
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: transaction_service_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: transaction_service_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: transaction_service_worker
    env_file:
      - .env
    command: ["python", "worker.py"]
    depends_on:
      - db
      - redis


volumes:
  postgres_data:


